-- spec/ecs/components/health_spec.lua
local Health = require('src.ecs.components.health')

describe('Health Component', function()
  it('should create with default values', function()
    local health = Health:new()
    assert.are.equal(100, health.max)
    assert.are.equal(100, health.current)
  end)

  it('should create with custom max HP', function()
    local health = Health:new(50)
    assert.are.equal(50, health.max)
    assert.are.equal(50, health.current)
  end)

  it('should create with custom current HP', function()
    local health = Health:new(100, 75)
    assert.are.equal(100, health.max)
    assert.are.equal(75, health.current)
  end)

  describe(':takeDamage()', function()
    it('should reduce current HP', function()
      local health = Health:new(100, 100)
      local died = health:takeDamage(30)
      assert.are.equal(70, health.current)
      assert.is_false(died)
    end)

    it('should return true when HP reaches zero', function()
      local health = Health:new(100, 30)
      local died = health:takeDamage(30)
      assert.are.equal(0, health.current)
      assert.is_true(died)
    end)

    it('should not go below zero', function()
      local health = Health:new(100, 30)
      health:takeDamage(50)
      assert.are.equal(0, health.current)
    end)
  end)

  describe(':heal()', function()
    it('should increase current HP', function()
      local health = Health:new(100, 50)
      health:heal(20)
      assert.are.equal(70, health.current)
    end)

    it('should not exceed max HP', function()
      local health = Health:new(100, 90)
      health:heal(20)
      assert.are.equal(100, health.current)
    end)
  end)

  describe(':isDead()', function()
    it('should return false when alive', function()
      local health = Health:new(100, 50)
      assert.is_false(health:isDead())
    end)

    it('should return true when HP is zero', function()
      local health = Health:new(100, 0)
      assert.is_true(health:isDead())
    end)
  end)

  describe(':getPercent()', function()
    it('should return correct percentage', function()
      local health = Health:new(100, 75)
      assert.are.equal(0.75, health:getPercent())
    end)

    it('should return zero when dead', function()
      local health = Health:new(100, 0)
      assert.are.equal(0, health:getPercent())
    end)
  end)
end)
