-- spec/ecs/components/transform_spec.lua
local Transform = require('src.ecs.components.transform')

describe('Transform Component', function()
  it('should create with default values', function()
    local t = Transform:new()
    assert.are.equal(0, t.x)
    assert.are.equal(0, t.y)
    assert.are.equal(0, t.rotation)
  end)

  it('should create with custom position', function()
    local t = Transform:new(100, 200)
    assert.are.equal(100, t.x)
    assert.are.equal(200, t.y)
  end)

  it('should create with custom rotation', function()
    local t = Transform:new(0, 0, 3.14)
    assert.are.equal(3.14, t.rotation)
  end)

  describe(':setPosition()', function()
    it('should update position', function()
      local t = Transform:new()
      t:setPosition(50, 60)
      assert.are.equal(50, t.x)
      assert.are.equal(60, t.y)
    end)
  end)

  describe(':translate()', function()
    it('should add to current position', function()
      local t = Transform:new(10, 20)
      t:translate(5, 10)
      assert.are.equal(15, t.x)
      assert.are.equal(30, t.y)
    end)
  end)

  describe(':getPosition()', function()
    it('should return x and y', function()
      local t = Transform:new(100, 200)
      local x, y = t:getPosition()
      assert.are.equal(100, x)
      assert.are.equal(200, y)
    end)
  end)

  describe(':setRotation()', function()
    it('should set rotation directly', function()
      local t = Transform:new()
      t:setRotation(1.57)
      assert.are.equal(1.57, t.rotation)
    end)
  end)

  describe(':rotate()', function()
    it('should add to current rotation', function()
      local t = Transform:new(0, 0, 1.0)
      t:rotate(0.5)
      assert.are.equal(1.5, t.rotation)
    end)
  end)
end)
