-- spec/ecs/components/velocity_spec.lua
local Velocity = require('src.ecs.components.velocity')

describe('Velocity Component', function()
  it('should create with default values', function()
    local v = Velocity:new()
    assert.are.equal(0, v.x)
    assert.are.equal(0, v.y)
    assert.are.equal(300, v.maxSpeed)
    assert.are.equal(0.9, v.friction)
  end)

  it('should create with custom values', function()
    local v = Velocity:new(10, 20, 500, 0.8)
    assert.are.equal(10, v.x)
    assert.are.equal(20, v.y)
    assert.are.equal(500, v.maxSpeed)
    assert.are.equal(0.8, v.friction)
  end)

  describe(':set()', function()
    it('should set velocity and clamp', function()
      local v = Velocity:new(0, 0, 100)
      v:set(50, 50)
      assert.are.equal(50, v.x)
      assert.are.equal(50, v.y)
    end)

    it('should clamp to maxSpeed', function()
      local v = Velocity:new(0, 0, 100)
      v:set(100, 100)
      local speed = v:getSpeed()
      assert.is_true(speed <= 100)
    end)
  end)

  describe(':add()', function()
    it('should add to velocity', function()
      local v = Velocity:new(10, 10)
      v:add(5, 5)
      assert.are.equal(15, v.x)
      assert.are.equal(15, v.y)
    end)
  end)

  describe(':applyFriction()', function()
    it('should reduce velocity by friction', function()
      local v = Velocity:new(100, 0, 300, 0.5)
      v:applyFriction()
      assert.are.equal(50, v.x)
      assert.are.equal(0, v.y)
    end)
  end)

  describe(':getSpeed()', function()
    it('should return correct magnitude', function()
      local v = Velocity:new(3, 4)
      assert.are.equal(5, v:getSpeed())
    end)

    it('should return zero for stationary', function()
      local v = Velocity:new()
      assert.are.equal(0, v:getSpeed())
    end)
  end)

  describe(':clamp()', function()
    it('should not modify velocity under maxSpeed', function()
      local v = Velocity:new(30, 40, 100) -- speed = 50
      v:clamp()
      assert.are.equal(30, v.x)
      assert.are.equal(40, v.y)
    end)

    it('should clamp velocity over maxSpeed', function()
      local v = Velocity:new(60, 80, 100) -- speed = 100, max = 100
      v:set(100, 0) -- speed = 100, exact at limit
      assert.are.equal(100, v.x)
      assert.are.equal(0, v.y)
    end)
  end)
end)
