-- spec/enemies/enemy_factory_spec.lua
local EnemyFactory = require('src.enemies.enemy_factory')
local Health = require('src.ecs.components.health')

describe('EnemyFactory', function()
  describe('.createBat()', function()
    it('should create a bat enemy', function()
      local bat = EnemyFactory:createBat(100, 200)

      assert.is_not_nil(bat)
      assert.are.equal('bat', bat.type)
      assert.are.equal(100, bat.transform.x)
      assert.are.equal(200, bat.transform.y)
    end)

    it('should have low HP', function()
      local bat = EnemyFactory:createBat(0, 0)
      assert.are.equal(20, bat.health.max)
      assert.are.equal(20, bat.health.current)
    end)

    it('should have high speed', function()
      local bat = EnemyFactory:createBat(0, 0)
      assert.is_true(bat.speed > 100)
    end)

    it('should have chase behavior', function()
      local bat = EnemyFactory:createBat(0, 0)
      assert.is_not_nil(bat.behavior)
      assert.are.equal('chase', bat.behavior.type)
    end)

    it('should have collider', function()
      local bat = EnemyFactory:createBat(0, 0)
      assert.is_not_nil(bat.collider)
      assert.is_number(bat.collider.w)
      assert.is_number(bat.collider.h)
    end)
  end)

  describe('.createGolem()', function()
    it('should create a golem enemy', function()
      local golem = EnemyFactory:createGolem(300, 400)

      assert.is_not_nil(golem)
      assert.are.equal('golem', golem.type)
      assert.are.equal(300, golem.transform.x)
      assert.are.equal(400, golem.transform.y)
    end)

    it('should have high HP', function()
      local golem = EnemyFactory:createGolem(0, 0)
      assert.are.equal(80, golem.health.max)
      assert.are.equal(80, golem.health.current)
    end)

    it('should have low speed', function()
      local golem = EnemyFactory:createGolem(0, 0)
      assert.is_true(golem.speed < 80)
    end)

    it('should have patrol behavior', function()
      local golem = EnemyFactory:createGolem(0, 0)
      assert.is_not_nil(golem.behavior)
      assert.are.equal('patrol', golem.behavior.type)
    end)
  end)

  describe('.createFromType()', function()
    it('should create bat by type string', function()
      local enemy = EnemyFactory:createFromType('bat', 100, 200)
      assert.are.equal('bat', enemy.type)
    end)

    it('should create golem by type string', function()
      local enemy = EnemyFactory:createFromType('golem', 100, 200)
      assert.are.equal('golem', enemy.type)
    end)

    it('should throw error for unknown type', function()
      assert.has_error(function()
        EnemyFactory:createFromType('unknown', 0, 0)
      end)
    end)
  end)
end)
